### ISSUE TITLE
谢谢分享！一点点小请求

### ISSUE THREAD

**Issue by nowislewis** [Eatzhy/Surface-defect-Detection-dataset#1]
请问有广东铝材数据集的标注文件嘛，网盘里面都是图片，有的压缩包还要解压密码没办法使用。但真的很感谢你收集了这么多数据，给了我很大的帮助。

**Comment by Eatzhy** [comment]
标注文件没有呀，官方没给。




| |
张阳
|
|
邮箱：zhygou@163.com
|

签名由 网易邮箱大师 定制

在2020年05月27日 14:15，lewisliuyi 写道：

请问有广东铝材数据集的标注文件嘛，网盘里面都是图片，有的压缩包还要解压密码没办法使用。但真的很感谢你收集了这么多数据，给了我很大的帮助。

**Comment by nowislewis** [comment]
> 标注文件没有呀，官方没给。 | | 张阳 | | 邮箱：zhygou@163.com | 签名由 网易邮箱大师 定制 在2020年05月27日 14:15，lewisliuyi 写道： 请问有广东铝材数据集的标注文件嘛，网盘里面都是图片，有的压缩包还要解压密码没办法使用。但真的很感谢你收集了这么多数据，给了我很大的帮助。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯嗯，那我自己标注吧。请问您有那些压缩包的解压密码吗？谢谢您的收集和帮助

**Comment by Eatzhy** [comment]
我找找没密码的文件，上传到盘上




| |
张阳
|
|
邮箱：zhygou@163.com
|

签名由 网易邮箱大师 定制

在2020年05月29日 22:08，lewisliuyi 写道：

标注文件没有呀，官方没给。 | | 张阳 | | 邮箱：zhygou@163.com | 签名由 网易邮箱大师 定制 在2020年05月27日 14:15，lewisliuyi 写道： 请问有广东铝材数据集的标注文件嘛，网盘里面都是图片，有的压缩包还要解压密码没办法使用。但真的很感谢你收集了这么多数据，给了我很大的帮助。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯嗯，那我自己标注吧。请问您有那些压缩包的解压密码吗？谢谢您的收集和帮助
